# Metadata for all Bacon test suites. For options, see:
# https://oktawiki.atlassian.net/wiki/spaces/ESS/pages/635280223/Flexible+Test+Suites
test_suites:
  # Required test suites
  - name: unit-test
    script_path: okta-idx-swift/ci-build
    sort_order: '1'
    timeout: '10'
    script_name: unit-test
    criteria: MERGE
    queue_name: apple-ci
  - name: ui-test
    script_path: okta-idx-swift/ci-build
    sort_order: '2'
    timeout: '60'
    script_name: ui-test
    criteria: MERGE
    queue_name: apple-ci
