version: 1
builder:
  configs:
    - documentation_targets:
        - AuthFoundation
        - OAuth2Auth
        - OktaDirectAuth
        - OktaIdxAuth
        - BrowserSignin
      custom_documentation_parameters:
        - "--enable-experimental-combined-documentation"
        - "--enable-experimental-mentioned-in"
        - "--experimental-skip-synthesized-symbols"
        - "--enable-experimental-external-link-support"
