language: swift
os: osx
osx_image: xcode12.5
before_install:
  - touch TestCredentials.xcconfig
jobs:
  include:
    - stage: Test
      name: iOS Unit Tests
      script:
      - xcodebuild -workspace okta-idx.xcworkspace -scheme "okta-idx-ios" -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" clean test
    # Disable UI tests in Travis until OktaSdk is public
    #- stage: Test
    #  name: iOS Automated Tests
    #  script:
    #  - xcodebuild -workspace okta-idx.xcworkspace -scheme "OktaIdxExample" -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" clean test
    - stage: Package Management
      name: Swift Package Manager
      script:
      - swift test
    - stage: Package Management
      name: Cocoapods
      script:
      - pod lib lint
    - stage: Package Management
      name: Carthage
      script:
      - carthage build --use-xcframeworks --no-skip-current
