name: Upload Build Cache
runs:
  using: composite
  steps:
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        path: ~/iOS-Build.tgz
        name: iOS-Build
        retention-days: 1
