name: Publish Documentation

on:
  push:
    branches:
      - master
    tags:
      - '*'

env:
  DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer
  DOCC_JSON_PRETTYPRINT: YES
  NSUnbufferedIO: YES

# NOTE: The DocC `generate-documentation` plugin does not handle the 
#       hostingBasePath well. In particular, it doesn't properly handle
#       multiple child paths. Furthermore, the current 1.0.0 version of
#       the plugin doesn't handle updates to the index.html or *.js
#       files.
#
#       This workflow should be revisited once Xcode 14 GA is released
#       so the newer DocC utilities can be utilized.
jobs:
  PublishToGHPages:
    name: Publish to Github Pages
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Define version information
      run: |
        set +ex
        VERSION=${{ github.ref_name }}
        if [[ "$VERSION" = "master" ]]; then
            VERSION=development
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
    - name: Build Documentation
      run: |
        set -e

        for TARGET in $(swift package describe --type json | jq ".products[].name" | sed -e 's/"//g'); do
            echo "Building $TARGET"
            NAME=$(echo "$TARGET" | tr '[:upper:]' '[:lower:]')
            mkdir -p docs/$VERSION/$NAME
            swift package \
                --allow-writing-to-directory docs \
                generate-documentation \
                --target $TARGET \
                --disable-indexing \
                --transform-for-static-hosting \
                --hosting-base-path okta-idx-swift/$VERSION/$NAME \
                --output-path docs/$VERSION/$NAME
            sed -I -e "s#<head>#<head><meta http-equiv='refresh' content='0;url=./documentation/$NAME/'>#" \
                docs/$VERSION/$NAME/index.html
        done
    - name: Deploy documentation to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        keep_files: true
