version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.9
  macos: circleci/macos@2

executors:
  apple-ci-arm-medium:
    macos:
      xcode: 15.4.0
    resource_class: macos.m1.medium.gen1

jobs:
  setup:
    executor: apple-ci-arm-medium
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  snyk-scan:
    executor: apple-ci-arm-medium
    steps:
      - attach_workspace:
          at: ~/project
      - macos/install-rosetta
      - run:
          name: run swift package show dependencies
          command: swift package show-dependencies
      - general-platform-helpers/step-load-dependencies
      - general-platform-helpers/step-run-snyk-monitor:
          scan-all-projects: true
          skip-unresolved: false
          os: macos

workflows:
  security-scan:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - master
      - general-platform-helpers/job-snyk-prepare:
          name: prepare-snyk
          requires:
            - setup
      - snyk-scan:
          name: execute-snyk
          requires:
            - prepare-snyk
