swift:
  - version: "5.10"
    xcode_versions: 
      - "15.4"
  - version: "6.0"
    xcode_versions: 
      - "16.0"
      - "16.1"
      - "16.2"
  - version: "6.1"
    xcode_versions: 
      - "16.3"
