name: Setup Shared Secrets
inputs:
  okta_plist:
    description: 'Okta.plist contents'
    required: true
  test_configuration:
    description: 'TestConfiguration.xcconfig contents'
    required: true
runs:
  using: composite
  steps:
    - name: Write Okta.plist
      run: echo "::add-mask::${{ inputs.okta_plist }}" > Samples/WebSignIn/Okta.plist
      shell: bash
    - name: Write TestConfiguration.xcconfig
      run: echo "::add-mask::${{ inputs.test_configuration }}" > Samples/Shared/TestConfiguration.xcconfig
      shell: bash
