name: Restore Build Cache
runs:
  using: composite
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        path: ~/Build
        name: iOS-Build
    - name: Prepare build artifacts
      shell: bash
      run: |
        mkdir ../Build
        tar -xzpf ~/Build/iOS-Build.tgz --strip-components=1 -C ..
        ls -lah ../Build
        find ../Build -type f -exec touch '{}' ';'
