name: Build and Unit Test

on:
  push:
    branches:
      - master
      - dev-*
      - release-*
  pull_request:
    branches: 
      - master
      - dev-*
      - release-*

jobs:
  Build:
    name: Unit Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    steps:
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@master
    - name: Build
      run: swift build --build-tests
    - name: Test
      run: swift test
