name: Lint code

on:
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - '.swiftlint.yml'
      - 'Sources/**/*.swift'
      - 'Samples/**/*.swift'
  push:
    paths:
      - '.github/workflows/lint.yml'
      - '.swiftlint.yml'
      - 'Sources/**/*.swift'
      - 'Samples/**/*.swift'
    branches:
      - master

jobs:
  SwiftLint:
    runs-on: macos-latest-large
    steps:
      - uses: actions/checkout@v1
      - name: Lint code using SwiftLint
        run: swiftlint lint --reporter github-actions-logging Sources Samples
