name: Preflight

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  DetectChanges:
    name: Detect Relevant Changes
    if: ${{ !(github.event.pull_request.draft || false) }}
    runs-on: ubuntu-latest
    outputs:
      is_master_or_tagged: ${{ steps.check_master.outputs.is_master_or_tagged }}
      changed_files: ${{ steps.list_changed_files.outputs.changed_files }}
      has_source_changes: ${{ steps.check_source_changes.outputs.has_source_changes }}
      has_documentation_changes: ${{ steps.check_documentation_changes.outputs.has_documentation_changes }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for Merge into Master or Release Tag
        id: check_master
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" || "${{ github.ref }}" == refs/tags/* ]]; then
            echo "Merging into master or a tag"
            echo "is_master_or_tagged=true" >> $GITHUB_OUTPUT
          else
            echo "is_master_or_tagged=false" >> $GITHUB_OUTPUT
          fi

      - name: List Changed Files
        id: list_changed_files
        run: |
          if [[ -z "${{ github.event.before }}" ]] || ! git cat-file -e ${{ github.event.before }} 2>/dev/null; then
            echo "No valid 'before' commit found. Listing all changes."
            git diff --name-only HEAD > changes
          else
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changes
          fi

          {
            echo 'changed_files<<EOF'
            cat changes
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Check for Unit Test Changes
        id: check_source_changes
        run: |
          if grep -qE '^(Sources/|Tests/|Package|.github/workflows/(preflight|tests).yaml)' changes; then
            echo "Has source changes"
            echo "has_source_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_source_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for Documentation Changes
        id: check_documentation_changes
        run: |
          if grep -qE '^(Sources/.*\.(md|swift)|.github/workflows/documentation.yaml)' changes; then
            echo "Has documentation changes"
            echo "has_documentation_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_documentation_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Debug outputs
        run: |
          cat $GITHUB_OUTPUT

  SwiftLint:
    name: Lint Sources
    needs: DetectChanges
    if: ${{ needs.DetectChanges.outputs.has_source_changes == 'true' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint code using SwiftLint
        run: |
          if ! which -s swiftlint; then
            echo "Installing SwiftLint..."
            brew install swiftlint
          fi

          swiftlint lint --reporter github-actions-logging Sources
