name: Xcode Build and Test

on:
  push:
    branches:
      - master
      - dev-*
      - release-*
  pull_request:
    branches:
      - master
      - dev-*
      - release-*

jobs:
  Build:
    name: Build SDK (${{ matrix.Platform }})
    runs-on: macos-latest
    strategy:
      matrix:
        Platform:
          - iphonesimulator
          - appletvsimulator
          - macosx
    steps:
    - uses: actions/checkout@master
    - name: Resolve package dependencies
      run: |
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme AuthFoundation \
            -resolvePackageDependencies
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme OktaOAuth2 \
            -resolvePackageDependencies
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme WebAuthenticationUI \
            -resolvePackageDependencies
    - name: Build AuthFoundation
      run: |
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme AuthFoundation \
            -sdk ${{ matrix.Platform }} \
            build
    - name: Build OktaOAuth2
      run: |
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme OktaOAuth2 \
            -sdk ${{ matrix.Platform }} \
            build
    - name: Build WebAuthenticationUI
      if: ${{ matrix.Platform != 'appletvsimulator' }}
      run: |
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme WebAuthenticationUI \
            -sdk ${{ matrix.Platform }} \
            build
    - name: Cache build directory
      uses: actions/cache@v2
      id: restore-build
      with:
        path: Build
        key: ${{ github.sha }}-${{ matrix.Platform }}

  WebSignIn:
    name: Web Sign In / Single Sign On (iOS)
    needs: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/setup-secrets
      with:
        okta_plist: "${{ secrets.TEST_OKTA_PLIST }}"
        test_configuration: "${{ secrets.TEST_CONFIGURATION }}"
    - name: Restore build directory
      uses: actions/cache@v2
      id: restore-build
      with:
        path: Build
        key: ${{ github.sha }}-iphonesimulator
    - name: Look up stuff
      run: find Build -type d
    - name: Test Web Sign In
      run: |
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme "WebSignIn (iOS)" \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.4' \
            test
    - name: Test Single Sign In
      run: |
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme "SingleSignOn (iOS)" \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.4' \
            test
    - name: Look up stuff
      run: find Build -type d

  DeviceAuthSignIniOS:
    name: Device Auth Sign In (iOS)
    needs: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/setup-secrets
      with:
        okta_plist: "${{ secrets.TEST_OKTA_PLIST }}"
        test_configuration: "${{ secrets.TEST_CONFIGURATION }}"
    - name: Restore build directory
      uses: actions/cache@v2
      id: restore-build
      with:
        path: Build
        key: ${{ github.sha }}-iphonesimulator
    - name: Test
      run: |
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme "DeviceAuthSignIn (iOS)" \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.4' \
            test

  DeviceAuthSignIntvOS:
    name: Device Auth Sign In (tvOS)
    needs: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/setup-secrets
      with:
        okta_plist: "${{ secrets.TEST_OKTA_PLIST }}"
        test_configuration: "${{ secrets.TEST_CONFIGURATION }}"
    - name: Restore build directory
      uses: actions/cache@v2
      id: restore-build
      with:
        path: Build
        key: ${{ github.sha }}-appletvsimulator
    - name: Look up stuff
      run: find Build -type d
    - name: Test
      run: |
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme "DeviceAuthSignIn (tvOS)" \
            -destination 'platform=tvOS Simulator,name=Apple TV,OS=15.4' \
            test
    - name: Look up stuff after
      run: find Build -type d

  UserPasswordSignInmacOS:
    name: User Password Sign In (macOS)
    needs: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/setup-secrets
      with:
        okta_plist: "${{ secrets.TEST_OKTA_PLIST }}"
        test_configuration: "${{ secrets.TEST_CONFIGURATION }}"
    - name: Restore build directory
      uses: actions/cache@v2
      id: restore-build
      with:
        path: Build
        key: ${{ github.sha }}-macosx
    - name: Test
      run: |
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme "UserPasswordSignIn (macOS)" \
            test
