name: Xcode Build and Test

on:
  push:
    branches:
      - master
      - dev-*
      - release-*
  pull_request:
    branches:
      - master
      - dev-*
      - release-*

jobs:
  Build:
    name: Build SDK on ${{ matrix.Platform }}
    runs-on: macos-12
    strategy:
      matrix:
        Platform:
          - iphonesimulator
          - appletvsimulator
          - macosx
    steps:
    - uses: actions/checkout@master
    - name: Resolve package dependencies
      run: |
        xcodebuild \
            -derivedDataPath DerivedData \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme AuthFoundation \
            -resolvePackageDependencies
        xcodebuild \
            -derivedDataPath DerivedData \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme OktaOAuth2 \
            -resolvePackageDependencies
        xcodebuild \
            -derivedDataPath DerivedData \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme WebAuthenticationUI \
            -resolvePackageDependencies
    - name: Build AuthFoundation
      run: |
        xcodebuild \
            -derivedDataPath DerivedData \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme AuthFoundation \
            -sdk ${{ matrix.Platform }} \
            build
    - name: Build OktaOAuth2
      run: |
        xcodebuild \
            -derivedDataPath DerivedData \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme OktaOAuth2 \
            -sdk ${{ matrix.Platform }} \
            build
    - name: Build WebAuthenticationUI
      run: |
        xcodebuild \
            -derivedDataPath DerivedData \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme WebAuthenticationUI \
            -sdk ${{ matrix.Platform }} \
            build
    - name: Cache build directory
      uses: actions/cache@v2
      id: restore-build
      with:
        path: DerivedData
        key: ${{ github.sha }}-${{ matrix.Platform }}

  WebSignIn:
    name: Web Sign In / Single Sign On
    needs: Build
    runs-on: macos-12
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/setup-secrets
      with:
        okta_plist: "${{ secrets.TEST_OKTA_PLIST }}"
        test_configuration: "${{ secrets.TEST_CONFIGURATION }}"
    - name: Restore build directory
      uses: actions/cache@v2
      id: restore-build
      with:
        path: DerivedData
        key: ${{ github.sha }}-iphonesimulator
    - name: Test Web Sign In
      run: |
        xcodebuild \
            -derivedDataPath DerivedData \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme "WebSignIn (iOS)" \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.4' \
            test
    - name: Test Single Sign In
      run: |
        xcodebuild \
            -derivedDataPath DerivedData \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme "SingleSignOn (iOS)" \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.4' \
            test

  DeviceAuthSignIniOS:
    name: Device Auth Sign In iOS
    needs: Build
    runs-on: macos-12
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/setup-secrets
      with:
        okta_plist: "${{ secrets.TEST_OKTA_PLIST }}"
        test_configuration: "${{ secrets.TEST_CONFIGURATION }}"
    - name: Restore build directory
      uses: actions/cache@v2
      id: restore-build
      with:
        path: DerivedData
        key: ${{ github.sha }}-iphonesimulator
    - name: Test
      run: |
        xcodebuild \
            -derivedDataPath DerivedData \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme "DeviceAuthSignIn (iOS)" \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.4' \
            test

  DeviceAuthSignIntvOS:
    name: Device Auth Sign In tvOS
    needs: Build
    runs-on: macos-12
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/setup-secrets
      with:
        okta_plist: "${{ secrets.TEST_OKTA_PLIST }}"
        test_configuration: "${{ secrets.TEST_CONFIGURATION }}"
    - name: Restore build directory
      uses: actions/cache@v2
      id: restore-build
      with:
        path: DerivedData
        key: ${{ github.sha }}-appletvsimulator
    - name: Test
      run: |
        xcodebuild \
            -derivedDataPath DerivedData \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme "DeviceAuthSignIn (tvOS)" \
            -destination 'platform=tvOS Simulator,name=Apple TV,OS=15.4' \
            test

  UserPasswordSignInmacOS:
    name: Device Auth Sign In tvOS
    needs: Build
    runs-on: macos-12
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/setup-secrets
      with:
        okta_plist: "${{ secrets.TEST_OKTA_PLIST }}"
        test_configuration: "${{ secrets.TEST_CONFIGURATION }}"
    - name: Restore build directory
      uses: actions/cache@v2
      id: restore-build
      with:
        path: DerivedData
        key: ${{ github.sha }}-appletvsimulator
    - name: Test
      run: |
        xcodebuild \
            -derivedDataPath DerivedData \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme "UserPasswordSignIn (macOS)" \
            -destination 'platform=macOS,name=Any Mac' \
            test
